version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '12345'
    ports:
      - '5432:5432'
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'luis.developer.ac@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '12345'
    ports:
      - '8080:8080'
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
