GET http://localhost:5000/student

###

POST http://localhost:5000/student
Content-Type: application/json

{
  "name": "Luis Santiago",
  "birthday": "2001-02-05T05:00:00.000Z"
}

###

POST http://localhost:5000/student
Content-Type: application/json

{
  "name": "Ezequiel da Silva Soares",
  "birthday": "2001-02-05T05:00:00.000Z",
  "guardian": {
    "name": "Tonhão da Silva Junior",
    "phone": "11999999999"
  }
}
