GET http://localhost:5000/student

###

POST http://localhost:5000/student
Content-Type: application/json

{
  "name": "Luis Antonio",
  "birthday": "2001-02-05T05:00:00.000Z",
  "gender": 1
}

###

POST http://localhost:5000/student
Content-Type: application/json

{
  "name": "Ezequiel da Silva Soares",
  "birthday": "2001-02-05T05:00:00.000Z",
  "gender": 1,
  "guardian": {
    "name": "Tonhão da Silva Junior",
    "phone": "11999999999"
  }
}

###

POST http://localhost:5000/student
Content-Type: application/json

{
  "name": "Maria Clara",
  "birthday": "2003-08-15T05:00:00.000Z",
  "gender": 2,
  "is_pwd": false,
  "race": 3,
  "status": 1,
  "email": "maria.clara@example.com",
  "address": "123 Main St, Anytown, USA",
  "phone": "1234567890",
  "facebook": "maria.clara",
  "instagram": "maria.clara",
  "tiktok": "maria.clara",
  "job": "Student",
  "education_level": "High School",
  "course": "Science"
}
