GET http://localhost:4000

###

GET http://localhost:4000/dashboard?id=72cf0be5-bcaa-4b7b-a535-7177b8e462e5

###

GET http://localhost:4000/students

###

POST http://localhost:4000/people
Content-Type: application/json

{
  "name": "Luis Antonio",
  "birthday": "2001-02-05T05:00:00.000Z",
  "gender": 1,
  "email": "luis.developer.ac@gmail.com"
}

###

POST http://localhost:4000/people
Content-Type: application/json

{
  "name": "Antônio Barbosa da Silva",
  "birthday": "1974-05-26T00:00:00.000Z",
  "gender": 1,
  "phone": "6899728955"
}

###

GET http://localhost:4000/people/e2f267d9-7b3e-410d-b4a7-2e360b94a6f0
Content-Type: application/json

###

PATCH http://localhost:4000/people/d92f84f9-6e3f-4798-9a13-aa09120d1800
Content-Type: application/json

{
  "name": "Luís Antônio Lima Santiago",
  "phone": "68992065657",
  "email": "luis.developer.ac@gmail.com",
  "gender": 1,
  "birthday": "2001-02-05T05:00:00.000Z",
  "updated_at": "2024-10-26T18:48:0.000Z",
  "nickname": "Tonhao",
  "is_pwd": false,
  "race": 3,
  "status": 1,
  "address": "Rua muito engraçada",
  "facebook": "luis_santiago",
  "instagram": "tonhao.dev",
  "tiktok": "tonhao.dev",
  "job": "Desenvolvimento de Software",
  "education_level": "Superior Incompleto",
  "course": "Tecnologia em Sistemas para a Internet",
  "year_start_capoeira": 2017,
  "effective_capoeira_training_time": 4,
  "year_of_last_belt_promotion": 2024,
  "trained_in_a_different_group": false,
  "first_capoeira_teacher": "Professor Alladin",
  "belt_id": "53879732-952b-4c16-8159-f5434e4b3352",
  "center_id": "35423623-f284-47a8-936e-d46ae7d1adf3",
  "current_teacher_id": "392be016-28ad-4cf9-a1c2-b623d8a36777"
}

###

PATCH http://localhost:4000/people/ac4246d5-9625-4b82-8ff8-5d04fed4e940
Content-Type: application/json

{
  "center_id": "a101d8d7-28b1-42e9-a134-87f911426639"
}

###

GET http://localhost:4000/people/e2f267d9-7b3e-410d-b4a7-2e360b94a6f0
Content-Type: application/json

###

DELETE http://localhost:4000/people/e6c9ed14-0d88-4131-9695-42e81dbd05ca
Content-Type: application/json

###

DELETE http://localhost:4000/people/00000000-0000-0000-0000-000000000000
Content-Type: application/json

###

POST http://localhost:4000/logout

###

PATCH http://localhost:4000/people/ed8e325a-2b28-4c73-bb20-9ce5e41bb910/graduateToTeacher

###

GET http://localhost:4000/teachers

###

PATCH http://localhost:4000/teachers/7d8346f9-09b0-4f4f-ad1f-293dc5171bbe/revokeTeacherStatus

###

GET http://localhost:4000/belts

###

GET http://localhost:4000/centers

###

GET http://localhost:4000/centers/52496971-d573-4760-b8c4-3f50c9d9d686

###

POST http://localhost:4000/centers
Content-Type: application/json

{
  "name": "Centro de Treinamento do Tonhas",
  "address": "Endereco do tonhas"
}

###

PATCH http://localhost:4000/centers/52496971-d573-4760-b8c4-3f50c9d9d686
Content-Type: application/json

{
  "name": "Centro de Treinamento do Tonhao",
  "address": "Endereco do tonhao",
  "latitude": -8.777777,
  "longitude": -70.555555
}

###

DELETE http://localhost:4000/centers/0e393e56-3396-4d93-aec4-81bf90227a0a
Content-Type: application/json

###

PATCH http://localhost:4000/teachers/392be016-28ad-4cf9-a1c2-b623d8a36777/updateCenter
Content-Type: application/json

{
  "center_id": "35423623-f284-47a8-936e-d46ae7d1adf3"
}
