import { Knex } from 'knex';

export async function seed(knex: Knex) {
  await knex('belt').del();
  await knex('belt').insert([
    {
      name: 'cinza',
      title: 'aluno',
      color_hex_code: '#5d5d5d',
      belt_type_code: 'BABY',
      order: 1,
    },
    {
      name: 'verde com pompom cinza',
      title: 'aluno',
      color_hex_code: '#1b9123,#5d5d5d',
      belt_type_code: 'BABY',
      order: 2,
    },
    {
      name: 'amarelo com pompom cinza',
      title: 'aluno',
      color_hex_code: '#f8f007,#5d5d5d',
      belt_type_code: 'BABY',
      order: 3,
    },
    {
      name: 'laranja com pompom cinza',
      title: 'aluno',
      color_hex_code: '#ff7300,#5d5d5d',
      belt_type_code: 'BABY',
      order: 4,
    },
    {
      name: 'azul claro com pompom cinza',
      title: 'aluno',
      color_hex_code: '#00fff6,#5d5d5d',
      belt_type_code: 'BABY',
      order: 5,
    },
    {
      name: 'cinza',
      title: 'aluno',
      color_hex_code: '#5d5d5d',
      belt_type_code: 'INFANTIL',
      order: 6,
    },
    {
      name: 'cinza e verde',
      title: 'aluno',
      color_hex_code: '#5d5d5d,#1b9123',
      belt_type_code: 'INFANTIL',
      order: 7,
    },
    {
      name: 'cinza e amarelo',
      title: 'aluno',
      color_hex_code: '#5d5d5d,#f8f007',
      belt_type_code: 'INFANTIL',
      order: 8,
    },
    {
      name: 'cinza e laranja',
      title: 'aluno',
      color_hex_code: '#5d5d5d,#ff7300',
      belt_type_code: 'INFANTIL',
      order: 9,
    },
    {
      name: 'cinza e azul claro',
      title: 'aluno',
      color_hex_code: '#5d5d5d,#00fff6',
      belt_type_code: 'INFANTIL',
      order: 10,
    },
    {
      name: 'cinza',
      title: 'aluno',
      color_hex_code: '#5d5d5d',
      belt_type_code: 'INFANTOJUVENIL',
      order: 11,
    },
    {
      name: 'azul claro e verde',
      title: 'aluno',
      color_hex_code: '#00fff6,#1b9123',
      belt_type_code: 'INFANTOJUVENIL',
      order: 12,
    },
    {
      name: 'azul claro e amarelo',
      title: 'aluno',
      color_hex_code: '#00fff6,#f8f007',
      belt_type_code: 'INFANTOJUVENIL',
      order: 13,
    },
    {
      name: 'azul claro e laranja',
      title: 'aluno',
      color_hex_code: '#00fff6,#ff7300',
      belt_type_code: 'INFANTOJUVENIL',
      order: 14,
    },
    {
      name: 'cinza',
      title: 'aluno',
      color_hex_code: '#5d5d5d',
      belt_type_code: 'ADULTO',
      order: 15,
    },
    {
      name: 'verde',
      title: 'aluno',
      color_hex_code: '#1b9123',
      belt_type_code: 'ADULTO',
      order: 16,
    },
    {
      name: 'verde e amarelo',
      title: 'aluno',
      color_hex_code: '#1b9123,#f8f007',
      belt_type_code: 'ADULTO',
      order: 17,
    },
    {
      name: 'amarelo',
      title: 'aluno',
      color_hex_code: '#f8f007',
      belt_type_code: 'ADULTO',
      order: 18,
    },
    {
      name: 'amarelo e laranja',
      title: 'aluno',
      color_hex_code: '#f8f007,#ff7300',
      belt_type_code: 'ADULTO',
      order: 19,
    },
    {
      name: 'laranja',
      title: 'aluno',
      color_hex_code: '#ff7300',
      belt_type_code: 'ADULTO',
      order: 20,
    },
    {
      name: 'azul claro',
      title: 'aluno',
      color_hex_code: '#00fff6',
      belt_type_code: 'ADULTO',
      order: 21,
    },
    {
      name: 'verde escuro',
      title: 'graduado',
      color_hex_code: '#154919',
      belt_type_code: 'ADULTO',
      order: 22,
    },
    {
      name: 'verde escuro e azul escuro',
      title: 'instrutor',
      color_hex_code: '#154919,#080d86',
      belt_type_code: 'ADULTO',
      order: 23,
    },
    {
      name: 'azul escuro',
      title: 'formado',
      color_hex_code: '#080d86',
      belt_type_code: 'ADULTO',
      order: 24,
    },
    {
      name: 'roxo',
      title: 'professor',
      color_hex_code: '#8f0581',
      belt_type_code: 'ADULTO',
      order: 25,
    },
    {
      name: 'roxo e marrom',
      title: 'contramestre 1° grau',
      color_hex_code: '#8f0581,#480201',
      belt_type_code: 'ADULTO',
      order: 26,
    },
    {
      name: 'marrom',
      title: 'contramestre 2° grau',
      color_hex_code: '#480201',
      belt_type_code: 'ADULTO',
      order: 27,
    },
    {
      name: 'vermelho',
      title: 'mestre 1° grau',
      color_hex_code: '#ff0000',
      belt_type_code: 'ADULTO',
      order: 28,
    },
    {
      name: 'vermelho e branco',
      title: 'mestre 2° grau',
      color_hex_code: '#ff0000,#ffffff',
      belt_type_code: 'ADULTO',
      order: 29,
    },
    {
      name: 'branco',
      title: 'mestre 3° grau',
      color_hex_code: '#ffffff',
      belt_type_code: 'ADULTO',
      order: 30,
    },
    {
      name: 'azul claro e azul escuro',
      title: 'estagiário',
      color_hex_code: '#00fff6,#080d86',
      belt_type_code: 'ADULTO',
      order: 31,
    },
  ]);
}
